### ISSUE TITLE
Single/double click behavior in calendar not consistent

### ISSUE THREAD

**Issue by adamehunt** [srg-kostyrko/obsidian-journal#35]
Thank you for the plugin.

I tried it today, and I noticed the clicking behavior on a day/week/month note to open/create a new note in the calendar wasn't consistent.

Sometimes I could single click to open/create a new note, and sometimes I had to double click. What is the intended behavior?

**Comment by srg-kostyrko** [comment]
No, this sounds like some issue.

Have you noticed any pattern to when it happens?
And could you please check Developer console (View - Toogle Developer Tools) next time you see this problem if there are any errors in it.

**Comment by adamehunt** [comment]
The issue happens on my laptop with the built in trackpad, but not when I have it docked using a mouse.

Here are the errors I could see

plugin:dbfolder:485 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'style')
    at QW (plugin:dbfolder:485:74013)
    at VV.constructUI (plugin:dbfolder:487:68686)
    at HV.display (plugin:dbfolder:487:69855)
    at SettingsSearch.getTabResources (plugin:settings-search:229:15)
    at SettingsSearch.buildPluginResources (plugin:settings-search:129:12)
    at eval (plugin:settings-search:131:29)
QW @ plugin:dbfolder:485
constructUI @ plugin:dbfolder:487
display @ plugin:dbfolder:487
getTabResources @ plugin:settings-search:229
buildPluginResources @ plugin:settings-search:129
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
plugin:dataview:12763 Dataview: Dropped cache entries for 3 deleted files.
plugin:file-explorer-note-count:867 <div class=​"tree-item-inner nav-folder-title-content">​Vault​</div>​ styles empty
eval @ plugin:file-explorer-note-count:867
plugin:file-explorer-note-count:867 <div class=​"tree-item-inner nav-folder-title-content">​Vault​</div>​ styles empty
eval @ plugin:file-explorer-note-count:867
setInterval (async)
FileExplorerNoteCount.doHiddenRoot @ plugin:file-explorer-note-count:865
eval @ plugin:file-explorer-note-count:904
tryGetView @ plugin:file-explorer-note-count:896
doWithFileExplorer @ plugin:file-explorer-note-count:899
eval @ plugin:file-explorer-note-count:922
2plugin:obsidian-icon-folder:594 loaded icon pack font-awesome-regular (163)
app.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'getRoot')
    at t.revealLeaf (app.js:1:2226060)
    at Object.callback (plugin:journals:5058:36)
    at aK (app.js:1:1988302)
    at t.onChooseItem (app.js:1:2590875)
    at t.eval (plugin:hotkey-helper:1:8654)
    at t.r [as onChooseItem] (plugin:hotkey-helper:1:880)
    at t.onChooseSuggestion (app.js:1:1564832)
    at t.selectSuggestion (app.js:1:1564382)
    at e.useSelectedItem (app.js:1:1562663)
    at Object.func (app.js:1:1560062)
t.revealLeaf @ app.js:1
callback @ plugin:journals:5058
aK @ app.js:1
t.onChooseItem @ app.js:1
eval @ plugin:hotkey-helper:1
r @ plugin:hotkey-helper:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
(anonymous) @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1

**Comment by srg-kostyrko** [comment]
hm the error in console is somehow connected to `hotkey-helper` plugin
could you please share how you used it together with journals plugin

**Comment by tmllull** [comment]
Hi! I have the same issue.

I don't know how to reproduce it 100%, but sometimes seems like the first click just act as "focus" to the calendar, and the others just work fine. But not always.

PS: I'm not using the `hotkey-helper`

**Comment by srg-kostyrko** [comment]
I released 2.0.0 with lots of changes to how calendar works
Please give it a try to see if it solves this problem

**Comment by srg-kostyrko** [comment]
Closing issue as stale, feel free to reopen it if you still see the problem
