### ISSUE TITLE
V2 rewamp

### ISSUE THREAD

**Issue by srg-kostyrko** [srg-kostyrko/obsidian-journal#63]
I'm starting work on V2 of plugin that will be quite big revamp on code level to make further development of plugin easier and also simplify introducing several planned features. 

And while most changes are on code level there will be also changes visible to user (plus I plan to include some new features in v2 as well): 
 - I getting rid of several journal types (calendar and interval) - `journal` will be set of notes that you write on regular basis - daily, weekly, monthly or some custom period (like every 2 weeks). So instead of one calendar journal that includes daily and weekly notes for example there will be 2 separate journals.
 - Introducing journal shelves - a way to group several journals in settings (similar to calendar journal right now) and also to control calendar view (to limit it only to some shelf)
 - start/end will be available in all journals (now it is only in interval ones)
 - indexing will be available in all journals (now it is only in interval ones)
 - it will be possible to define several templates (to allow complex scenarios - like template for specific days of week + generic one for others)
 - it will be possible to configure commands for specific journal
 - Configurable highlights for calendar view and code blocks

I created a separate project to track progress - https://github.com/users/srg-kostyrko/projects/3
The list of items there is preliminary and might grow as I work on changes.

The development will be going in separate branch `v2-dev`.

I also consider releasing beta version using BRAT plugin if there will be anyone interested in checking it out before final release.

**Comment by MMoMM-org** [comment]
the link to the project doesn't work for me.

Any idea when you are going to release v2 and how migration from v1 will look like?

I just wanted to switch from Periodic Notes to Journals, which I can only do on the 1st of January.
Reasons:
- Weekly, Monthly, Quarterly and Yearly Reviews with Dataview Extracts
- around 6 Templates or more which hook into those notes or are those notes
So recreating those templates to work with Journals is a lot of work if I want to make changes to them to use the frontmatter implemented with Journals.

Needing to switch those templates around again and also figure out how to make all dataview etc work with two different kinds of  configuration will be a pain, so I guess I will probably need to wait  for another year to implement the use of the frontmatter properties.

**Comment by srg-kostyrko** [comment]
> the link to the project doesn't work for me.

🤦  project was private, should be available now

I hope to release v2 beta in January (main changes are ready, testing/polishing now, the only big thing left is migration itself - as I planned to do it at the very and to have everything else stable)
Migration will be automated and providing ability to adjust some settings before starting corresponding journal notes updates.

the only big change in frontmatter that is not backward compatible would be splitting 1 calendar journal into up to 5 journals (depending on what was enabled) and removing `journal-section` as result

so for example instead of 
```yaml
journal: My notes
journal-section: day
```yaml
in daily notes
and
```
journal: My notes
journal-section: week
```
in weekly note 

it will change into
```yaml
journal: My daily notes
```
and 
```yaml
journal: My weekly notes
```
correspondingly (name change will be configured as part of migration process)

not sure about complexity of your dataviews so hard to tell if migration goes without issues
I can add a setting to optionally add journal type (journal-section right now) into frontmatter  if you plan to use it and it helps you with switching (it was necessary before when daily and weekly notes were in same journal, but after change it is no longer necessary so will be removed as part of migration)

> There will still be the issue with the codeblocks which will be present in all the notes. I wonder if that will be an issue for me.
not sure what issue you mention here, could you please explain more

**Comment by MMoMM-org** [comment]
I think my codeblocks are a non issue, and the other code too. I'm just refraining from using journal and journal-section atm in the code.
One question though as I just played around with the calender of journals.
How do you manage all the different journals in the calendar in v2?
I had 3 different journals configured and found it cumbersome
-  to click on a date
- get 3 different "Journals" presented 
- and then need to click on one to get to the date note

I wonder how this will work with 5 different journals now for day, week, month, quarter, year plus 2 more

**Comment by srg-kostyrko** [comment]
In calendar when you click on a date only daily journals are present in dropdown (and if there is only 1 such journal - there is no menu and note is opened right away) - this stays the same in v2
There will also be a concept of `shelf` - you can group multiple journals into a shelf and then use just one shelf in calendar view (with a setting of default shelf and a command to quickly change shelf in calendar). This will simplify context switching between journals

**Comment by caesiumtea** [comment]
Will V2 work with existing V1 journals, or will we need to set up new journals under V2? I just found this plugin today and I'm wondering whether I should wait until V2 is released before I start using it.

**Comment by marcus-crane** [comment]
> Will V2 work with existing V1 journals, or will we need to set up new journals under V2? I just found this plugin today and I'm wondering whether I should wait until V2 is released before I start using it.

Sergii mentions earlier in the thread that there will be an automatic migration apparently:

> Migration will be automated and providing ability to adjust some settings before starting corresponding journal notes updates.

**Comment by srg-kostyrko** [comment]
yes there will be automated migration so feel free to start using plugin

**Comment by srg-kostyrko** [comment]
I finally released 2.0.0.beta1 - it took me longer than I expected.
The beta1 version is now available through BRAT plugin.

I would be grateful to anyone who can give it a try and give me feedback. 

I tried my best to test it through, but the changes were quite big so I might have missed something.
So a better start would probably be to try it first on a vault copy. There is a data migration for existing notes but it is not reversible (though the only thing it could break is plugin settings and plugin frontmatter properties).

For now, I plan to keep it in beta for a couple of weeks and after that release it (unless there are some critical problems).

**Comment by marcus-crane** [comment]
Hey @srg-kostyrko,

I just ran the beta-1 on a copy of my vault and it seemed to work although I noticed a few bugs:

- Metadata conversion appears to work fine at a brief glance
- Renaming a journal post-migration appears to break associations with journal entries. I'm not sure if this is intended but I guess I would expect a journal rename to also rewrite frontmatter? Also, for weekly notes, renaming and then reverting back to the original name doesn't appear to fix the associations. Renaming and reverting for monthly notes seemed to work fine.
- Attempting to create a new note of any type using the calendar widget in the right sidebar throws `Error: File already exists` in the console, even though the file does not exist and doesn't get created either. Opening existing files works fine.
- The left and right arrows within the date picker modal for "End writing" don't appear to work. Selecting a month works however.
- When doing the migration, I found that the first journal migration had some sort of progress bar (blurred in the background? The whole process was quite far). Doing the next journal migration however would show no progress, just with an instant next button that didn't do anything. Closing the modal and then selecting the migrate option in settings picked up progress again but I had to manually exit and restart the migration for all remaining journals

Happy to provide more detail and/or a recording if you like as well. This was just a few quick notes from a fast runthrough.

**Comment by srg-kostyrko** [comment]
Big thanks for your feedback

> Renaming a journal post-migration appears to break associations with journal entries.

this seems to be some problem with establishing connection of migrated notes to journal, I will dig deeper here, but generally yes - renaming a journal should update all its notes with the new name, potentially you can try reloading Obsidian and see if that fixes this problem

> Attempting to create a new note of any type using the calendar widget in the right sidebar throws Error: File already exists in the console, even though the file does not exist and doesn't get created either. 

hm, work fine for me right now, could you add stack trace from that error? and also try if reopening Obsidian will fix the problem

> The left and right arrows within the date picker modal for "End writing" don't appear to work. Selecting a month works however.

Yeh, some issue with month arrows (year and decade ones work) - will fix it

> When doing the migration, I found that the first journal migration had some sort of progress bar (blurred in the background? The whole process was quite far). Doing the next journal migration however would show no progress, just with an instant next button that didn't do anything. Closing the modal and then selecting the migrate option in settings picked up progress again but I had to manually exit and restart the migration for all remaining journals

could you show some screenshots or do a recording here? Migration might be quick especially if there are not many notes and as soon as you see Next button - it means that step is finished. Maybe it is not very clear from UI

**Comment by srg-kostyrko** [comment]
Can you provide some examples of how this looks like in other plugins you refer to? Is it some code block? Or how is it added to a note?

**Comment by marcus-crane** [comment]
I'll do a full recording of the migration later today. I'd have fleshed out the post a bit more but it was a little past midnight when I ran it 😅

**Comment by srg-kostyrko** [comment]
@marcus-crane 
I found and fixed the issue with renaming a journal (that is did not update note properties) - will probably release beta2 as it might be quite an issue for anyone using beta1

as for ` Error: File already exists` - could not reproduce it, so if you see it again - please provide stacktrace from that error from console

**Comment by X1n0s1lv4** [comment]
> ![[journals/{{date:YYYY}}/{{[W]w}}]]

That was it! Awesome! 

I managed to do it with a little tweak: 

![[Journal/Weekly/{{date:YYYY-[W]ww}}#Next week goals]] 

I understand the downsides. 
The first one I don't intend to do it. 
The second one might cause some bug, but now that you mentioned it I can be attentive. 

Many thanks for your help!

**Comment by X1n0s1lv4** [comment]
I also got a suggestion that heard from another plug-in... 
In the calendar view: 

<img width="260" alt="Image" src="https://github.com/user-attachments/assets/b4e803dd-b32f-448b-a9ad-b3ae342a437f" />

Those dots below the dates and week, represent that there is a note associated with that day. 
I think would be nice to add more dots to represent when a note is bigger. 

The example I've heard is that, each dot represent 250 words (can be programmable). 
That is helpful to visualise, when moving through the days in which days we wrote more... 

I thought that could be a relatively simple thing to add...

**Comment by srg-kostyrko** [comment]
It is not that simple - unfortunately obsidian does not provide word count so I'll have to write something here
Calendar decorations in Journals are way more complex compared to what other plugins have so it will function a bit differently. 
I added an issue that describes this change - https://github.com/srg-kostyrko/obsidian-journal/issues/105.
For now I'm not sure when I'll work on it.

**Comment by srg-kostyrko** [comment]
I released v2.0.0.beta2 with journal renaming fix (and couple minor text polishes)

**Comment by X1n0s1lv4** [comment]
> It is not that simple - unfortunately obsidian does not provide word count so I'll have to write something here Calendar decorations in Journals are way more complex compared to what other plugins have so it will function a bit differently. I added an issue that describes this change - [#105](https://github.com/srg-kostyrko/obsidian-journal/issues/105). For now I'm not sure when I'll work on it.

Ok! I don't really know how to program the plug ins so I don't really know how hard it is. 
Anyways, thank you for your dedication. Maybe one day that can be possible.

**Comment by ChristinWhite** [comment]
The only annoyance I'm running into right now is its insistence to move the calendar into the main explorer group each time Obsidian loads. 

![Screenshot of the calendar above the Explorer group panel with an arrow from the Calendar toolbar icon pointing to the right of the items in the Explorer panel grouop.](https://github.com/user-attachments/assets/ae36d61d-fb85-4ecd-80bd-1553ae116c69)

**Comment by srg-kostyrko** [comment]
Good point - will fix it

**Comment by ChristinWhite** [comment]
Just ran into another minor issue with creating custom commands. Right now if the command name has a space in it, say `Open Today` command ID doesn't encode the space with a dash like most commands, so you get something like: `journals:Personal:Open Today`. 

This can cause compatibility issues for other plugins that run commands and don't have a way to handle that situation, such as [Vimrc Support](https://github.com/esm7/obsidian-vimrc-support/tree/master) ([related issue](https://github.com/esm7/obsidian-vimrc-support/issues/169)). I'm not sure how many other plugins this is true of, but if there's one, there are likely others.

**Comment by srg-kostyrko** [comment]
I was not aware of such limitations - I'll fix it

**Comment by JokeNeverSoke** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/14816406?u=7c063678599238503afb4b9d05f348186acba61d&amp;v=4&amp;size=80">@marcus-crane](https://github.com/marcus-crane?rgh-link-date=2025-02-18T06%3A59%3A20.000Z) I found and fixed the issue with renaming a journal (that is did not update note properties) - will probably release beta2 as it might be quite an issue for anyone using beta1
> 
> as for ` Error: File already exists` - could not reproduce it, so if you see it again - please provide stacktrace from that error from console

I have been encountering the same error on beta2 - when attempting to create a new daily note with commands or from the calendar view. Navigating to existing notes work fine.

Further investigating, the confirmation dialog do pop up when creating a new daily, but no file is created after confirmation.
Error below:

```
Error: File already exists.
    at t.<anonymous> (app.js:1:751955)
    at app.js:1:239667
    at Object.next (app.js:1:239772)
    at a (app.js:1:238490)
```

Weekly notes work normally.

**Comment by marcus-crane** [comment]
I still need to generate that recording I promised 😉

**Comment by srg-kostyrko** [comment]
> I have been encountering the same error on beta2 - when attempting to create a new daily note with commands or from the calendar view. Navigating to existing notes work fine.
>
> Further investigating, the confirmation dialog do pop up when creating a new daily, but no file is created after confirmation.

@JokeNeverSoke 
I'm still unable to reproduce this. Most likely there is some combination of settings that causes this problem.
I've released beta3 where I added a bit of logs to note creation flow - please update the plugin, try reproducing the issue, and send me the logs from the console.
And if it is ok for you - please share your settings (data.json file from .obsidian\plugins\journals folder)

Also created https://github.com/srg-kostyrko/obsidian-journal/issues/107 as a future improvement for such investigations - the idea is to collect logs and give an easy way for used to enable them and output into a note

**Comment by JokeNeverSoke** [comment]
@srg-kostyrko Very unfortunately, I've fixed the issue before upgrading by deleting the journals entry (attached screenshot) add adding the daily journal again. I have been unable to reproduce the issue again myself.

![Image](https://github.com/user-attachments/assets/50a2ecbf-ff49-4fd5-be0d-899176603019)

Many thanks for the fantastic plugin btw. Awesome replacement for alternatives that saved my day.

**Comment by srg-kostyrko** [comment]
@JokeNeverSoke 
And was the deleted journal with problems a converted one from v1? Or was it created in v2?

**Comment by JokeNeverSoke** [comment]
The journal was imported from v1, yes.

**Comment by marcus-crane** [comment]
Here's a walkthrough of me migrating from v1 to v2 beta3 and running into the file creation issue.

It seems that a file with no name is trying to be created. In this case, `Private/Journal` is where mine lives and it's trying to create `Private/Journal/.md` which is an invalid action.

<video src="https://cdn.utf9k.net/video/journalv2beta3.mp4"></video>

**Comment by srg-kostyrko** [comment]
Aha, now I get what you meant about restarting migration - will try to reproduce and fix

With creation, it fails to build filename apparently 
Could you please check if date format and name template settings were correctly migrated and filled in

**Comment by srg-kostyrko** [comment]
@marcus-crane 
I couldn't get fully similar migration behavior as in video 
It does not get stuck for me
The only idea I have for now - you have some calendar journals where all sections are disabled. 
Am I right?
If yes - how would you expect such journal to be migrated? Are that some older journals kept just for notes?
and if you don't mind - could you send me your `data.json` file from plugin v1 to srg.kostyrko@gmail.com, I would like to experiment migrating it.

as for the file creation problem - I found the problem in the migration script and fixed it, thanks for the logs - that helped much

**Comment by marcus-crane** [comment]
>  The only idea I have for now - you have some calendar journals where all sections are disabled.
>  If yes - how would you expect such journal to be migrated? Are that some older journals kept just for notes?

That's correct, yep. I did a daily journal last year (and backfilled some previous entries) so I just left it configured in case I ever want to jump back to a certain date and see what I was up to.

I don't think I've explicitly disabled anything (in v1 at least)? The shelf configurations are just whatever occured by default as I haven't used v2 beyond testing out the migration 🙂

I'll send you through my data.json file for you

**Comment by srg-kostyrko** [comment]
@marcus-crane 
Big thanks for data.json - it helped me find and fix problems with migration
I released beta4 - please give it a try when you have time

this is last known problem as of now - unless I find something else today I plan to release v2 for everyone tomorrow.

**Comment by marcus-crane** [comment]
@srg-kostyrko Just confirming that all of the issues I experienced are all resolved now 🙂 Congrats on reaching v2!

**Comment by marcus-crane** [comment]
A few typos I spotted while migrating my main vault. There's also a mixture of "Shelfs" and "Shelves" as well

![Image](https://github.com/user-attachments/assets/6cea616a-2817-4746-ba4e-623a7c20cd20)

![Image](https://github.com/user-attachments/assets/2bbbc09c-c046-48e7-8ab8-40c7e13a9d64)

**Comment by srg-kostyrko** [comment]
Thanks for highlighting - will fix it

**Comment by srg-kostyrko** [comment]
v2 is officially out 🎉
